Alphabetical order YAML script for Istio org members
istio/community pull request #1107
Opened 2023-06-30 08:50 UTC by ronitblenz

## I want to join the Istio org!

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [X] I have written my company name or "Individual", if not affliated with a company, here: Individual
- [X] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, here: 

Resolves Issue #1092 

Approach 👍 

I have made a directory called members, where you can add your name randomly (so that if somebody messes up with the already existing order, it would not affect the main members.yaml file). Now the script sorts the YAML and makes a copy of the ```tempname.yaml``` to generate updated ```members.yaml```.

<img width="1440" alt="Screenshot 2023-06-30 at 1 27 53 PM" src="https://github.com/istio/community/assets/91361382/6e901349-cfe1-4f9e-ab51-ce854f212ba7">

2023-06-30 08:51 UTC, istio-testing commented
Hi @ronitblenz. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fcommunity).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-06-30 19:31 UTC, craigbox requested changes

2023-06-30 19:31 UTC, craigbox commented on org/members.yaml
To add yourself as a member, please send a different PR.

2023-07-03 13:18 UTC, ericvn commented
Can we not check in the temp_name.yaml and only generate it as needed to do the sort?

2023-07-17 22:04 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-07-18 03:33 UTC, ronitblenz commented
Ok let me make the required changes.

2024-02-16 01:53 UTC, craigbox commented
Hi Ronit,

Thanks for your contribution.  I'm going to close this PR as it has sat here for over 6 months.  If you're interested in revisiting this, I suggest you join the Istio Slack and check in with Eric or John in #contributors as to how you should change your code to best achieve this goal.

Good luck as you ramp up your contributions to open source.

2024-02-16 01:53 UTC, closed without merging