Add Salesforce representative
istio/community pull request #410
Opened 2020-08-25 13:46 UTC by pnambiarsf

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [ ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ ] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

2020-08-25 13:46 UTC, istio-testing commented
Hi @pnambiarsf. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fcommunity).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-08-25 14:03 UTC, craigbox requested changes

2020-08-25 14:03 UTC, craigbox commented on steering/README.md
> +&nbsp; | Pratima Nambiar | Salesforce | [pnambiarsf](https://github.com/pnambiarsf) | Contribution seat
Please sort yourself alphabetically between Sven and Louis.  Thanks!

2020-08-25 14:11 UTC, craigbox commented
/ok-to-test

2020-08-25 14:11 UTC, craigbox approved these changes

2020-08-26 01:19 UTC, pnambiarsf commented
@googlebot I signed it!

2020-08-26 01:21 UTC, merged