Remove developer who removed github account
istio/community pull request #508
Opened 2021-01-04 18:39 UTC by howardjohn

https://github.com/domgoer is now a 404

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [ ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ ] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

2021-01-04 18:50 UTC, craigbox commented
Appears to have been renamed to domechn

2021-01-04 18:57 UTC, craigbox requested changes

2021-01-04 18:57 UTC, craigbox commented on org/developers.yaml
>  - dmitri-d
```suggestion
- dmitri-d
- domechn
```

2021-01-04 18:57 UTC, craigbox commented on org/developers.yaml
>  - dmitri-d
@domechn to confirm

2021-01-04 19:26 UTC, craigbox approved these changes

2021-01-04 19:27 UTC, merged

2021-01-05 03:26 UTC, nrjpoddar commented
@howardjohn how are you finding inactive/deleted accounts? Is there automation that surfaces these accounts?

2021-01-05 03:27 UTC, howardjohn commented
The postsubmit job fails and sends a notification to slack/email

On Mon, Jan 4, 2021 at 7:26 PM Neeraj Poddar <notifications@github.com>
wrote:

> @howardjohn <https://github.com/howardjohn> how are you finding
> inactive/deleted accounts? Is there automation that surfaces these accounts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/community/pull/508#issuecomment-754366056>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXLONBB3MQ2WFAECUVDSYKBGBANCNFSM4VTMUAAA>
> .
>

2021-01-05 05:40 UTC, domechn commented on org/developers.yaml
>  - dmitri-d
confirmed, thanks for your modification