Add imroc as a member
istio/community pull request #803
Opened 2022-09-29 00:54 UTC by imroc

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
Tencent

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
https://github.com/istio/istio/pull/41203

2022-09-29 00:54 UTC, istio-testing commented
Hi @imroc. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fcommunity).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-29 01:02 UTC, Xunzhuo approved these changes

2022-09-29 01:03 UTC, kebe7jun approved these changes
Welcome!

2022-09-29 01:03 UTC, kebe7jun commented
/ok-to-test

2022-09-29 01:04 UTC, istio-testing commented
@imroc: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
test_community | baef56c2434402ae7f0b3396a2e7bf239da9aa2f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_community/803/test_community/1575290166195523584) | true | `/test test`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-29 01:04 UTC, kebe7jun requested changes

2022-09-29 01:04 UTC, kebe7jun commented on org/members.yaml
> +- imroc
needs sort list.

2022-09-29 01:29 UTC, hzxuzhonghu approved these changes

2022-09-29 01:59 UTC, istio-testing commented
@imroc: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
test_community | 7d1a1784aba2ca6530c00b33e9504623fd163966 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_community/803/test_community/1575304210696638464) | true | `/test test`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-29 02:06 UTC, kebe7jun approved these changes

2022-09-29 02:07 UTC, merged

2022-10-14 07:18 UTC, imroc commented
@kebe7jun 
Sorry I didn't notice the email before, the invitation is out of date, can you resend the invitation?

2022-10-14 07:22 UTC, kebe7jun commented
> @kebe7jun Sorry I didn't notice the email before, the invitation is out of date, can you resend the invitation?

I'm not familiar with how to do this, @craigbox  do you have experience to help imroc?

2022-10-15 00:23 UTC, imroc commented
> @kebe7jun Sorry I didn't notice the email before, the invitation is out of date, can you resend the invitation?

@howardjohn @dhawton Does anyone know how to do it? It is a bit troublesome to ask other members to "/ok-to-test" for each PR

2022-10-15 03:17 UTC, dhawton commented
I do not sorry.

2022-10-16 15:38 UTC, ericvn commented
Looking at the post submit job, it simply says it waiting for an acceptance. If I look at the member list in GitHub, I see an entry under pending invitations, and I only see the ability to edit an invite and cancel an invite, not to resend an invite. I did select to edit the invite, did not change it, and clicked to update. I'm not sure if that will send another invite or not. We could also cancel the invite, and then when the next community PR merges, the post-submit should then create a new invite (may need the PR to have a change in the members org to cause the job to run (would need to double-check)).

2022-10-16 15:42 UTC, imroc commented
> Looking at the post submit job, it simply says it waiting for an acceptance. If I look at the member list in GitHub, I see an entry under pending invitations, and I only see the ability to edit an invite and cancel an invite, not to resend an invite. I did select to edit the invite, did not change it, and clicked to update. I'm not sure if that will send another invite or not. We could also cancel the invite, and then when the next community PR merges, the post-submit should then create a new invite (may need the PR to have a change in the members org to cause the job to run (would need to double-check)).

@ericvn It works, thank you so much.